(define (domain sokoban)
  (:requirements :equality)
  (:predicates (has_player ?x)
               (has_box ?x)
               (n1 ?x ?y)
               (n2 ?x ?y))
  (:action move-player
           :parameters (?x ?y)
           :precondition (and (n1 ?x ?y)
                              (not (has_box ?y))
                              (has_player ?x))
           :effect		 (and (has_player ?y)
                              (not (has_player ?x))))
  (:action push-box
		   :parameters (?x ?y ?z)
		   :precondition (and   (has_player ?x)
                                (has_box ?y)
                                (not (has_box ?z))
                                (n1 ?x ?y)
                                (n1 ?y ?z)
                                (n2 ?x ?z))
	       :effect (and (has_box ?z)
						(not(has_box ?y))
						(has_player ?y)
						(not(has_player ?x))))
  )